version: "3"
services:
  ninspect:
    build: .
    volumes:
      - ./dump/:/dump/
    privileged: true

  hakchi:
    build: docker-hakchi
    volumes:
      - ./dump/:/hakchi/dump/
    devices:
      - /dev/bus/usb